# Generated by Django 4.2.1 on 2023-05-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('stock', 'Stock'), ('out_of_stock', 'Out of Stock')], default='stock', max_length=12),
        ),
    ]
