# Generated by Django 4.2.1 on 2023-05-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_image', models.ImageField(upload_to='images')),
                ('product_price', models.IntegerField()),
                ('product_offer', models.BooleanField(default=False)),
                ('product_status', models.CharField(choices=[('stock', 'Stock'), ('out_of_stock', 'Out of Stock')], default='stock', max_length=12)),
            ],
        ),
    ]
